spring:
  application:
    name: apptarjeta-backend
  profiles:
    default: json
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
server:
  port: 8080

app:
  data-directory: ./data
  cors:
    allowed-origins:
      - "http://localhost:5173"

---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/cmr_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
app:
  data-directory: ./data
